### ISSUE TITLE
TypeError: concat() got an unexpected keyword argument 'sort'

### ISSUE THREAD

**Issue by hugoncosta** [ShichenXie/scorecardpy#2]
I was following the tutorial and I had this error upon calculating train_pref:

---------------------------------------------------------------------------
```
TypeError                                 Traceback (most recent call last)
<ipython-input-70-707eda962142> in <module>()
      3 
      4 # performance ks & roc ------
----> 5 train_perf = sc.perf_eva(y_train, train_pred, title = "train")
      6 test_perf = sc.perf_eva(y_test, test_pred, title = "test")

/usr/local/lib/python3.6/dist-packages/scorecardpy/perf.py in perf_eva(label, pred, title, groupnum, plot_type, show_plot, positive, seed)
    280     # dfkslift ------
    281     if any([i in plot_type for i in ['ks', 'lift']]):
--> 282         dfkslift = eva_dfkslift(df, groupnum)
    283         if 'ks' in plot_type: df_ks = dfkslift
    284         if 'lift' in plot_type: df_lift = dfkslift

/usr/local/lib/python3.6/dist-packages/scorecardpy/perf.py in eva_dfkslift(df, groupnum)
     31       pd.DataFrame({'group':0, 'good':0, 'bad':0, 'good_distri':0, 'bad_distri':0, 'badrate':0, 'cumbadrate':np.nan, 'cumgood':0, 'cumbad':0, 'ks':0, 'lift':np.nan}, index=np.arange(1)),
     32       df_kslift
---> 33     ], ignore_index=True, sort=False)
     34     # return
     35     return df_kslift

TypeError: concat() got an unexpected keyword argument 'sort'
```

**Comment by ShichenXie** [comment]
This bug is caused by pandas' update, `concat` added `sort` argument in pandas 0.23, but no in the earlier versions. 
It should be fixed, please reinstall `scorecardpy` and try again.

**Comment by hugoncosta** [comment]
Error still happens. Using scorecardpy-0.1.6.1 (installed via github).

**Comment by ShichenXie** [comment]
If you still got the same error, you might not install `scorecardpy` properly. There is no `sort=False` in the line 33 on [perf.py](https://github.com/ShichenXie/scorecardpy/blob/master/scorecardpy/perf.py).

**Comment by hugoncosta** [comment]
Yeah, I see that. It's odd, since I do use the `pip install git+git://github.com/shichenxie/scorecardpy.git` to install it. I'll wait for these changes to be on the PYPI.

**Comment by ShichenXie** [comment]
Actually, I have upload the latest version package to PYPI. You can check the source code from https://pypi.org/project/scorecardpy/#files.

I suggest you to use anaconda for the python environment, which saves your time on managing the packages.

**Comment by hugoncosta** [comment]
I'm using Google Colab, tried with both sources and the error subsists unfortunately :( anyway, I've done what I wanted on R, there eveything worked, so thanks!

**Comment by Danish366** [comment]
@hugoncosta You need to update your pandas module in Google Colab as they have the previous version installed. Use: `!pip install pandas --upgrade`. That should fix the issue.
